server:
  port: 8080

spring:
  application:
    name: test_dictionary
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update